language: erlang
otp_release:
  - 17.0
notifications:
  recipients:
    - anotherworldofworld@gmail.com
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && git checkout v0.14.1 && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - MIX_ENV=test mix do deps.get, compile
script:
  - mix test --no-start
env:
  - MIX_ENV=test
